name: home
root: ~/dev/home

windows:
  - main:
      layout: main-vertical
      panes:
        - emacs -nw .
        - sudo python socket_server.py 
        - node_modules/.bin/sails lift
        - cd elm && ls src/*.elm | entr -cr elm make src/Main.elm --output=../assets/js/main.js
