name: home
root: ~/dev/home

windows:
  - main:
      layout: main-vertical
      panes:
        - emacs -nw .
        - cd switch-api && sudo python socket_server.py 
        - cd server && node_modules/.bin/sails lift
        - cd server/elm && ls src/*.elm | entr -cr elm make src/Main.elm --output=../assets/js/main.js
